# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
x = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
y = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
x = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
y = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [19]:
x = np.arange(0,10).reshape(2,5)
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [21]:
x = np.arange(0,15).reshape(3,5)
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [22]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [26]:
x = np.arange(1,26).reshape(5,5)
np.power(x,2)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [28]:
x = np.arange(1,31).reshape(5,6)
np.mean(x)

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
x = np.arange(1,31).reshape(5,6)
np.std(x)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [31]:
x = np.arange(1,31).reshape(5,6)
np.median(x)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [32]:
x = np.arange(1,31).reshape(5,6)
np.transpose(x)

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [35]:
x = np.arange(1,17).reshape(4,4)
np.trace(x)

34

## Question:13

### Find the determinant of the previous array in Q12?

In [36]:
x = np.arange(1,17).reshape(4,4)
np.linalg.det(x)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [38]:
x = np.arange(1,17).reshape(4,4)
print(np.percentile(x,5))
print(np.percentile(x,95))

1.75
15.25


## Question:15

### How to find if a given array has any null values?

In [52]:
x = np.array([[1,2],[5,np.NaN]])
np.isnan(x)

array([[False, False],
       [False,  True]])